WebApplication3/Models/Company.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication3.Models
{
    public class Company
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public ICollection<Employee> Users { get; set; }
    }
}

WebApplication3/Models/Employee.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication3.Models
{
    public class Employee
    {
        public int Id { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public int Age { get; set; }
        public int CompanyId { get; set; }
        
    }
}

WebApplication3/Models/EmployeeProfile.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;

namespace WebApplication3.Models
{
    public class EmployeeProfile
    {
    }
}

WebApplication3/Controllers/CompanyController.cs
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class CompanyController : Controller
    {
        CompaniesContext db = new CompaniesContext();

        public ActionResult Index()
        {
            var companies = db.Companies.ToList();
            return View(companies);
        }

        [HttpGet]
        public ActionResult Add()
        {
            ViewBag.Action = "Add";
            return View("Edit");
        }

        [HttpPost]
        public ActionResult Add(Company company)
        {
            company.Id = db.Companies.Count() + 1;
            db.Companies.Add(company);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            /*var company = companies.FirstOrDefault(p => p.Id == id);
            if (company != null)
            {
                ViewBag.Action = "Edit";
                return View(company);
            }*/

            return HttpNotFound();
        }
    }
}

WebApplication3/Controllers/EmployeeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using WebApplication3.Models;

namespace WebApplication3.Controllers
{
    public class EmployeeController : Controller
    {
        CompaniesContext db = new CompaniesContext();

        public EmployeeController()
        {
            
        }

        public ActionResult Index(int companyId)
        {
            IQueryable<Employee> employees = db.Employees;
            employees = employees.Where(p => p.CompanyId == companyId);
            ViewBag.CompanyId = companyId;
            return View(employees.ToList());
        }

        [HttpGet]
        public ActionResult Add(int companyId)
        {
            Employee employee = new Employee { CompanyId = companyId };
            ViewBag.Action = "Add";
            return View("Edit", employee);
        }

        [HttpPost]
        public ActionResult Add(Employee employee)
        {
            employee.Id = db.Employees.Count() + 1;
            db.Employees.Add(employee);
            db.SaveChanges();
            return RedirectToAction("Index", new { companyId=employee.CompanyId });
        }

        [HttpGet]
        public ActionResult Edit(int id)
        {
            var employee = db.Employees.FirstOrDefault(p => p.Id == id);
            if (employee != null)
            {
                ViewBag.Action = "Edit";
                return View(employee);
            }

            return HttpNotFound();
        }

        [HttpPost]
        public ActionResult Edit(Employee employee)
        {
            var oldEmployee = db.Employees.FirstOrDefault(p => p.Id == employee.Id);
            if (oldEmployee != null)
            {
                oldEmployee.FirstName = employee.FirstName;
                oldEmployee.LastName = employee.LastName;
                oldEmployee.Age = employee.Age;
            }
            db.Entry(oldEmployee).State = System.Data.Entity.EntityState.Modified;
            db.SaveChanges();
            return RedirectToAction("Index", new { companyId = employee.CompanyId });
        }

        [HttpGet]
        public ActionResult Delete(int id)
        {
            var employee = db.Employees.FirstOrDefault(p => p.Id == id);
            db.Employees.Remove(employee);
            db.SaveChanges();
            return RedirectToAction("Index", new { companyId = employee.CompanyId });
        }

    }
}

WebApplication3/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace WebApplication3.Controllers
{
    public class HomeController : Controller
    {
        public ActionResult Index()
        {
            return View();
        }

        public ActionResult About()
        {
            ViewBag.Message = "Your application description page.";

            return View();
        }

        public ActionResult Contact()
        {
            ViewBag.Message = "Your contact page.";

            return View();
        }
    }
}

WebApplication3/Views/Company/Edit.cshtml
@using WebApplication3.Models;
@model Company
@{string action = ViewBag.Action; }
@using (Html.BeginForm(action, "Company", FormMethod.Post))
{

    <table>
        @Html.HiddenFor(p => p.Id)
        <tr>
            <td>@Html.LabelFor(p => p.Name)</td>
            <td>@Html.TextBoxFor(p => p.Name)</td>
        </tr>


    </table>
    <button>Submit</button>

}

WebApplication3/Views/Company/Index.cshtml
@using WebApplication3.Models;
@model List<Company>

<table class="table table-striped">
    @foreach (var company in Model)
    {
    <tr>
        <td>@company.Name </td>
        <td><a href="/Company/Edit/@company.Id">Edit</a></td>
        <td><a href="/Company/Delete/@company.Id">Delete</a></td>
        <td><a href="/Employee?companyId=@company.Id">View Employees</a></td>
        <td><a href="/Employee/Add?companyId=@company.Id">Add new Employee</a></td>
    </tr>
    }
</table>
<div><a href="/Company/Add/">Add new company</a></div>

WebApplication3/Views/Employee/Edit.cshtml
@using WebApplication3.Models;
@model Employee
@{string action = ViewBag.Action; }
@using (Html.BeginForm(action, "Employee", FormMethod.Post))
{

    <table>
        @Html.HiddenFor(p => p.Id)
        @Html.HiddenFor(p => p.CompanyId)
        <tr>
            <td>@Html.LabelFor(p => p.LastName)</td>
            <td>@Html.TextBoxFor(p => p.LastName)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.FirstName)</td>
            <td>@Html.TextBoxFor(p => p.FirstName)</td>
        </tr>
        <tr>
            <td>@Html.LabelFor(p => p.Age)</td>
            <td>@Html.EditorFor(p => p.Age)</td>
        </tr>

    </table>
    <button>Submit</button>

}

WebApplication3/Views/Employee/Index.cshtml
@using WebApplication3.Models;
@model List<Employee>

<table class="table table-striped">
    @foreach (var employee in Model)
    {
    <tr>
        <td>@employee.FirstName </td>
        <td>@employee.LastName </td>
        <td>@employee.Age </td>
        <td><a href="/Employee/Edit/@employee.Id">Edit</a></td>
        <td><a href="/Employee/Delete/@employee.Id">Delete</a></td>
    </tr>
    }
</table>
<div><a href="/Employee/Add?CompanyId=@ViewBag.CompanyId">Add new user</a></div>

WebApplication3/Views/Home/About.cshtml
@{
    ViewBag.Title = "About";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<p>Use this area to provide additional information.</p>

WebApplication3/Views/Home/Contact.cshtml
@{
    ViewBag.Title = "Contact";
}
<h2>@ViewBag.Title.</h2>
<h3>@ViewBag.Message</h3>

<address>
    One Microsoft Way<br />
    Redmond, WA 98052-6399<br />
    <abbr title="Phone">P:</abbr>
    425.555.0100
</address>

<address>
    <strong>Support:</strong>   <a href="mailto:Support@example.com">Support@example.com</a><br />
    <strong>Marketing:</strong> <a href="mailto:Marketing@example.com">Marketing@example.com</a>
</address>

WebApplication3/Views/Home/Index.cshtml
@{
    ViewBag.Title = "Home Page";
}

<div class="jumbotron">
    <h1>ASP.NET</h1>
    <p class="lead">ASP.NET is a free web framework for building great Web sites and Web applications using HTML, CSS and JavaScript.</p>
    <p><a href="https://asp.net" class="btn btn-primary btn-lg">Learn more &raquo;</a></p>
</div>

<div class="row">
    <div class="col-md-4">
        <h2>Getting started</h2>
        <p>
            ASP.NET MVC gives you a powerful, patterns-based way to build dynamic websites that
            enables a clean separation of concerns and gives you full control over markup
            for enjoyable, agile development.
        </p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301865">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Get more libraries</h2>
        <p>NuGet is a free Visual Studio extension that makes it easy to add, remove, and update libraries and tools in Visual Studio projects.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301866">Learn more &raquo;</a></p>
    </div>
    <div class="col-md-4">
        <h2>Web Hosting</h2>
        <p>You can easily find a web hosting company that offers the right mix of features and price for your applications.</p>
        <p><a class="btn btn-default" href="https://go.microsoft.com/fwlink/?LinkId=301867">Learn more &raquo;</a></p>
    </div>
</div>

WebApplication3/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title - My ASP.NET Application</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
    <div class="navbar navbar-inverse navbar-fixed-top">
        <div class="container">
            <div class="navbar-header">
                <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                @Html.ActionLink("Application name", "Index", "Home", new { area = "" }, new { @class = "navbar-brand" })
            </div>
            <div class="navbar-collapse collapse">
                <ul class="nav navbar-nav">
                    <li>@Html.ActionLink("Home", "Index", "Home")</li>
                    <li>@Html.ActionLink("List of Employees", "Index", "Employee")</li>
                    <li>@Html.ActionLink("List of Companies", "Index", "Company")</li>
                </ul>
            </div>
        </div>
    </div>
    <div class="container body-content">
        @RenderBody()
        <hr />
        <footer>
            <p>&copy; @DateTime.Now.Year - My ASP.NET Application</p>
        </footer>
    </div>

    @Scripts.Render("~/bundles/jquery")
    @Scripts.Render("~/bundles/bootstrap")
    @RenderSection("scripts", required: false)
</body>
</html>